import React from "react";
import { 
  Play, Pause, Zap, Database, Terminal, FileText, 
  CheckCircle, Wifi 
} from "lucide-react";

interface OperationsConsoleProps {
  stateData: any;
  eventLogs: any[];
  onToggleSimulation: () => void;
  onSimulationSpeedChange: (speed: number) => void;
}

export default function OperationsConsole({ 
  stateData, 
  eventLogs, 
  onToggleSimulation, 
  onSimulationSpeedChange 
}: OperationsConsoleProps) {
  const sources = stateData?.ingestion_status || {};
  const sim = stateData?.simulation || { active: true, speed: 3 };

  const formatWatermark = (wm: any) => {
    if (!wm) return "N/A";
    const date = new Date(wm * 1000);
    return date.toLocaleTimeString();
  };

  const getSourceIcon = (srcName: string) => {
    switch (srcName.toLowerCase()) {
      case "mysql": return <Database className="w-5 h-5 text-blue-400" />;
      case "sftp": return <FileText className="w-5 h-5 text-amber-400" />;
      case "transunion": return <CheckCircle className="w-5 h-5 text-teal-400" />;
      default: return <Wifi className="w-5 h-5 text-purple-400" />;
    }
  };

  return (
    <div className="space-y-6 animate-fadeIn">
      {/* Simulation Controls */}
      <div className="bg-slate-900 border border-slate-800 rounded-xl p-5 shadow-lg flex flex-col md:flex-row md:items-center md:justify-between gap-4">
        <div>
          <h3 className="text-sm font-bold text-slate-200 uppercase tracking-wider flex items-center">
            <Zap className="w-4 h-4 mr-2 text-blue-400" />
            Kafka-Style Simulated Event Bus
          </h3>
          <p className="text-xs text-slate-400 mt-1">
            Simulate real-time raw events generated by subscriber device swaps and carrier ports
          </p>
        </div>

        <div className="flex items-center space-x-4">
          <button 
            onClick={onToggleSimulation}
            className={`px-4 py-2 rounded-lg font-bold text-xs flex items-center space-x-2 border transition-all ${
              sim.active 
                ? "bg-rose-500/10 text-rose-400 border-rose-500/30 hover:bg-rose-500/20" 
                : "bg-emerald-500/10 text-emerald-400 border-emerald-500/30 hover:bg-emerald-500/20"
            }`}
          >
            {sim.active ? (
              <>
                <Pause className="w-4 h-4" /> <span>Pause Simulation</span>
              </>
            ) : (
              <>
                <Play className="w-4 h-4" /> <span>Resume Simulation</span>
              </>
            )}
          </button>

          <div className="flex items-center space-x-2">
            <span className="text-xs text-slate-400">Interval:</span>
            <select 
              value={sim.speed}
              onChange={(e) => onSimulationSpeedChange(parseFloat(e.target.value))}
              className="bg-slate-950 border border-slate-800 rounded-lg px-3 py-1.5 text-xs text-slate-200 font-mono focus:border-blue-500 outline-none"
            >
              <option value="1">1.0s (Fast)</option>
              <option value="2">2.0s</option>
              <option value="3">3.0s (Normal)</option>
              <option value="5">5.0s (Slow)</option>
            </select>
          </div>
        </div>
      </div>

      {/* Ingestion Sources grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {Object.entries(sources).map(([key, val]: [string, any]) => (
          <div 
            key={key} 
            className="bg-slate-900 border border-slate-800 rounded-xl p-5 shadow-lg flex flex-col justify-between hover:border-slate-700 transition-all"
          >
            <div className="flex items-start justify-between border-b border-slate-800 pb-3 mb-4">
              <div className="flex items-center space-x-3">
                {getSourceIcon(key)}
                <div>
                  <h4 className="text-xs font-bold text-slate-200 uppercase tracking-wider">{key} Ingestion</h4>
                  <span className="text-[10px] font-mono text-slate-500">v{val.schema_version} schema</span>
                </div>
              </div>
              <span className={`px-2 py-0.5 rounded-full text-[9px] font-bold uppercase ${
                val.status === "streaming" 
                  ? "bg-blue-500/10 text-blue-400 border border-blue-500/20 animate-pulse" 
                  : "bg-slate-800 text-slate-400"
              }`}>
                {val.status}
              </span>
            </div>

            <div className="grid grid-cols-2 gap-4 text-xs font-mono mb-4">
              <div>
                <span className="text-slate-500 block">Ingested Rows:</span>
                <span className="text-slate-200 font-bold text-sm">{val.rows || 0}</span>
              </div>
              <div>
                <span className="text-slate-500 block">Watermark:</span>
                <span className="text-slate-300">{formatWatermark(val.watermark)}</span>
              </div>
            </div>

            <div className="text-[10px] text-slate-500 flex items-center justify-between border-t border-slate-800/60 pt-3">
              <span>Source Type: {key === "mysql" || key === "sftp" ? "Batch ETL" : "REST Streaming"}</span>
              <span className="text-emerald-500 flex items-center">
                <span className="w-1.5 h-1.5 bg-emerald-500 rounded-full mr-1"></span> Active Connection
              </span>
            </div>
          </div>
        ))}
      </div>

      {/* Kafka Topic Live Terminal */}
      <div className="bg-slate-900 border border-slate-800 rounded-xl p-5 shadow-lg space-y-4">
        <div className="flex items-center justify-between border-b border-slate-800 pb-3">
          <h3 className="text-sm font-bold text-slate-200 uppercase tracking-wider flex items-center">
            <Terminal className="w-4 h-4 mr-2 text-rose-500" />
            Kafka Topic: enstream.raw-carrier-events
          </h3>
          <span className="text-xs text-slate-500 font-mono">Consumer Offset: {eventLogs.length}</span>
        </div>

        <div className="bg-slate-950 font-mono text-xs rounded-xl p-4 border border-slate-800 max-h-[350px] overflow-y-auto space-y-2.5">
          {eventLogs.length === 0 ? (
            <div className="text-slate-600 italic text-center py-6">
              Listening to events on the Kafka event bus...
            </div>
          ) : (
            [...eventLogs].reverse().map((log, index) => (
              <div 
                key={index}
                className="py-2 px-3 hover:bg-slate-900/40 rounded flex flex-col md:flex-row md:items-center justify-between border-l-2 border-slate-800 hover:border-blue-500/50 transition-all"
              >
                <div className="space-y-0.5">
                  <span className="text-slate-500 font-bold">[{new Date(log.timestamp * 1000).toLocaleTimeString()}]</span>
                  <span className="text-blue-400 font-semibold uppercase ml-2">[{log.source}]</span>
                  <span className="text-slate-300 ml-2">Event: <span className="text-amber-400 font-semibold">{log.event_type}</span></span>
                  <span className="text-slate-400 ml-3">MSISDN: <span className="text-slate-100 font-mono">{log.msisdn}</span></span>
                </div>
                <span className="text-[10px] text-slate-500 font-mono mt-1 md:mt-0">id: {log.event_id}</span>
              </div>
            ))
          )}
        </div>
      </div>
    </div>
  );
}
